vesoft-inc/nebula-graph

- .github/workflows/pull_request.yml
- CMakeLists.txt
- src/executor/Executor.cpp
- src/executor/Executor.h
- src/executor/admin/ShowHostsExecutor.cpp
- src/executor/mutate/InsertExecutor.cpp
- src/executor/query/DataJoinExecutor.cpp
- src/executor/query/DataJoinExecutor.h
- src/executor/query/GetNeighborsExecutor.cpp
- src/executor/query/GetNeighborsExecutor.h
- src/executor/query/GetVerticesExecutor.cpp
- src/scheduler/Scheduler.cpp
- src/scheduler/Scheduler.h
- tests/common/nebula_service.py
- tests/requirements.txt
> Add open and close interfaces in Executor

- cmake/ConfigNebulaStorage.cmake
> Fix build error due to concurrently build nebula-common

- .dockerignore
- .github/workflows/docker.yml
- .github/workflows/pull_request.yml
- Dockerfile
- README.md
- package/package.sh
> Add docker build workflow and fix required checks skipped error

- Dockerfile
- conf/CMakeLists.txt
- package/CMakeLists.txt
- package/package.sh
- src/daemons/CMakeLists.txt
> Fix install prefix of package script

- CMakeLists.txt
- src/context/QueryExpressionContext.cpp
- src/context/QueryExpressionContext.h
- src/executor/query/test/FilterTest.cpp
- src/executor/query/test/LimitTest.cpp
- src/parser/CMakeLists.txt
- src/parser/GraphScanner.h
- src/parser/Sentence.h
- src/parser/parser.yy
- src/parser/scanner.lex
- src/parser/test/ParserTest.cpp
- src/util/ExpressionUtils.h
- src/util/test/ExpressionUtilsTest.cpp
- src/validator/FetchEdgesValidator.cpp
- src/validator/FetchVerticesValidator.cpp
- src/validator/GoValidator.cpp
- src/validator/MutateValidator.cpp
- src/validator/TraversalValidator.cpp
- src/validator/Validator.cpp
- tests/query/v1/test_yield.py
The syntax counterpart of vesoft-inc/nebula-common#207
> Add AttributeExpression

- .linters/cpp/checkKeyword.py
- src/parser/parser.yy
- src/parser/scanner.lex
- src/parser/test/CMakeLists.txt
- src/parser/test/ExpressionParsingTest.cpp
- src/parser/test/ParserTest.cpp
- src/validator/test/GroupByValidatorTest.cpp
* Add UT on expression parsing
* Support VariableExpression syntax
* Support NOT IN
CI depends on the fix at vesoft-inc/nebula-common#212
> Add expression parsing tests

- src/parser/TraverseSentences.h
- src/parser/parser.yy
- src/validator/test/FetchVerticesTest.cpp
- tests/query/v1/test_fetch_vertex.py
A part of https://github.com/vesoft-inc/nebula/pull/2222
> Let fetch vertices accept multi-vertices and input as vids when not specify tag.

- src/parser/Clauses.h
- src/parser/parser.yy
- src/util/ExpressionUtils.h
- src/validator/GoValidator.cpp
- src/validator/MutateValidator.cpp
- src/validator/TraversalValidator.cpp
- src/visitor/RewriteLabelAttrVisitor.cpp
> Simplify the replication of expression by clone function

- src/executor/Executor.cpp
- src/executor/Executor.h
- src/executor/logic/LoopExecutor.cpp
- src/executor/logic/LoopExecutor.h
- src/executor/logic/SelectExecutor.cpp
- src/executor/logic/SelectExecutor.h
- src/executor/test/LogicExecutorsTest.cpp
- src/planner/Logic.h
Fix cpplint warning about too looong function.
> Refactor executor make function

- src/context/Iterator.cpp
- src/context/test/IteratorTest.cpp
- tests/mutate/test_delete_vertices.py
- tests/query/v1/test_fetch_vertex.py
- tests/query/v1/test_go.py
- tests/query/v2/test_get_subgraph.py
depend on https://github.com/vesoft-inc/nebula-storage/pull/137
> change null value to empty value

- src/parser/parser.yy
- src/parser/scanner.lex
- src/parser/test/ParserTest.cpp
depend on [232](https://github.com/vesoft-inc/nebula-common/pull/232)
> Remove offline flag when rebuild index

- src/context/Iterator.cpp
- src/context/Iterator.h
- src/context/test/IteratorTest.cpp
- tests/common/nebula_test_suite.py
- tests/nebula-test-run.py
After https://github.com/vesoft-inc/nebula-common/pull/227
> Fix get edge.

- .gitignore
- src/context/test/CMakeLists.txt
- src/optimizer/OptimizerUtils.cpp
- src/parser/test/CMakeLists.txt
- src/util/CMakeLists.txt
- src/util/ExpressionUtils.cpp
- src/util/ExpressionUtils.h
- src/validator/YieldValidator.cpp
- src/validator/YieldValidator.h
- src/visitor/CMakeLists.txt
- src/visitor/FoldConstantExprVisitor.cpp
- src/visitor/FoldConstantExprVisitor.h
- src/visitor/test/CMakeLists.txt
- src/visitor/test/FoldConstantExprVisitorTest.cpp
depends on vesoft-inc/nebula-common#230
> Add constant expression folding visitor

- src/optimizer/CMakeLists.txt
- src/optimizer/rule/IndexScanRule.cpp
- src/optimizer/rule/IndexScanRule.h
- src/optimizer/test/CMakeLists.txt
- src/optimizer/test/IndexScanRuleTest.cpp
- src/planner/Query.h
- src/validator/IndexScanValidator.cpp
- src/validator/IndexScanValidator.h
- src/validator/Validator.cpp
Because private repo changed. close #181 and open this one.
Still in process.
> Optimizer rule for index scan

- .github/workflows/pull_request.yml
- ci/test.sh
Always clean nebula-python source directory in final step
> Fix CI failure caused by nebula-python folder

- src/optimizer/OptGroup.cpp
- src/optimizer/OptGroup.h
- src/optimizer/OptRule.cpp
- src/optimizer/OptRule.h
- src/optimizer/Optimizer.cpp
- src/optimizer/Optimizer.h
- src/optimizer/rule/IndexScanRule.cpp
- src/optimizer/rule/IndexScanRule.h
- src/optimizer/rule/LimitPushDownRule.cpp
- src/optimizer/rule/PushFilterDownGetNbrsRule.cpp
- src/optimizer/rule/TopNRule.cpp
- tests/query/v2/test_optimizer.py
> Rename group node of optimizer

- src/mock/test/TestMock.cpp
- src/parser/MaintainSentences.h
- src/util/SchemaUtil.cpp
- src/util/SchemaUtil.h
- src/util/ToJson.cpp
- src/validator/MaintainValidator.cpp
- src/validator/MaintainValidator.h
- tests/maintain/test_tag_edge.py
depends on vesoft-inc/nebula-common#211
> Support to save default value to expression

- src/validator/MutateValidator.cpp
- src/visitor/CMakeLists.txt
- src/visitor/RewriteSymExprVisitor.cpp
- src/visitor/RewriteSymExprVisitor.h
- tests/common/global_data_loader.py
- tests/nebula-test-run.py
> Rewrite sym expr access method by visitor and close graph client connection in data loader

- src/parser/test/ExpressionParsingTest.cpp
- src/visitor/CollectAllExprsVisitor.cpp
- src/visitor/ExprVisitorImpl.cpp
- src/visitor/FindAnyExprVisitor.cpp
- src/visitor/FoldConstantExprVisitor.cpp
- src/visitor/FoldConstantExprVisitor.h
- src/visitor/RewriteInputPropVisitor.cpp
- src/visitor/RewriteLabelAttrVisitor.cpp
- src/visitor/RewriteLabelAttrVisitor.h
- src/visitor/RewriteSymExprVisitor.cpp
depends on vesoft-inc/nebula-common#268, vesoft-inc/nebula-storage#177
> Update container expression usage

- src/context/test/CMakeLists.txt
- src/daemons/CMakeLists.txt
- src/executor/test/CMakeLists.txt
- src/mock/test/CMakeLists.txt
- src/optimizer/test/CMakeLists.txt
- src/parser/test/CMakeLists.txt
- src/util/test/CMakeLists.txt
- src/validator/test/CMakeLists.txt
- src/visitor/test/CMakeLists.txt
Follow https://github.com/vesoft-inc/nebula-common/pull/274
> Add object time_utils.

- src/daemons/GraphDaemon.cpp
Follow https://github.com/vesoft-inc/nebula-graph/pull/348
> Initialize the timezone configuration.

- src/validator/MatchValidator.cpp
- src/validator/MatchValidator.h
- tests/common/nebula_test_suite.py
- tests/data/nba.ngql
- tests/query/v2/test_match.py
> Added CI tests for MATCH

- .linters/cpp/checkKeyword.py
- src/parser/MatchSentence.cpp
- src/parser/MatchSentence.h
- src/parser/TraverseSentences.h
- src/parser/parser.yy
- src/parser/scanner.lex
- src/parser/test/ParserTest.cpp
- src/parser/test/ScannerTest.cpp
- src/validator/MatchValidator.cpp
- src/validator/MatchValidator.h
- src/validator/OrderByValidator.cpp
- src/validator/test/YieldValidatorTest.cpp
- tests/query/v2/test_match.py
Exceptions are:
* `CALL`
* Mutiple labels on one vertex.
> Added nearly fully syntatic support for MATCH

- src/parser/MatchSentence.h
- src/parser/TraverseSentences.h
- src/planner/Query.h
- src/planner/planners/MatchSolver.cpp
- src/validator/MatchValidator.cpp
- src/validator/MatchValidator.h
- src/validator/OrderByValidator.cpp
- tests/query/v2/test_match.py
TODO: `Sort` needs to be augmented to support general expressions as order factors.
> Add DISTINCT & ORDER BY & SKIP & LIMIT

- .linters/cpp/checkKeyword.py
- src/parser/parser.yy
- src/parser/scanner.lex
- src/parser/test/ExpressionParsingTest.cpp
- src/visitor/CollectAllExprsVisitor.cpp
- src/visitor/CollectAllExprsVisitor.h
- src/visitor/DeducePropsVisitor.h
- src/visitor/DeduceTypeVisitor.cpp
- src/visitor/DeduceTypeVisitor.h
- src/visitor/EvaluableExprVisitor.h
- src/visitor/ExprVisitorImpl.cpp
- src/visitor/ExprVisitorImpl.h
- src/visitor/ExtractFilterExprVisitor.h
- src/visitor/ExtractPropExprVisitor.cpp
- src/visitor/ExtractPropExprVisitor.h
- src/visitor/FindAnyExprVisitor.cpp
- src/visitor/FindAnyExprVisitor.h
- src/visitor/FoldConstantExprVisitor.cpp
- src/visitor/FoldConstantExprVisitor.h
- src/visitor/RewriteInputPropVisitor.cpp
- src/visitor/RewriteInputPropVisitor.h
- src/visitor/RewriteLabelAttrVisitor.cpp
- src/visitor/RewriteLabelAttrVisitor.h
- src/visitor/RewriteMatchLabelVisitor.cpp
- src/visitor/RewriteMatchLabelVisitor.h
- src/visitor/RewriteSymExprVisitor.cpp
- src/visitor/RewriteSymExprVisitor.h
- src/visitor/test/FoldConstantExprVisitorTest.cpp
- tests/query/v2/test_case_expression.py
- tests/query/v2/test_match.py
http://jira.nebula-graph.io:8081/projects/NG/issues/NG-281?filter=allissues
Based on:
https://github.com/vesoft-inc/nebula-common/pull/269
https://github.com/vesoft-inc/nebula-storage/pull/183
> Support case expression

- src/validator/FetchEdgesValidator.cpp
- src/validator/FetchVerticesValidator.cpp
- src/validator/GoValidator.cpp
- src/validator/MatchValidator.cpp
- src/validator/Validator.cpp
- src/validator/Validator.h
- src/validator/YieldValidator.cpp
- src/visitor/DeduceTypeVisitor.cpp
- src/visitor/DeduceTypeVisitor.h
- src/visitor/test/CMakeLists.txt
- src/visitor/test/DeduceTypeVisitorTest.cpp
- src/visitor/test/FoldConstantExprVisitorTest.cpp
- src/visitor/test/TestMain.cpp
- tests/query/v2/test_case_expression.py
- tests/query/v2/test_label_expr.py
After https://github.com/vesoft-inc/nebula-common/pull/296
> Fix deduce type.

- cmake/ConfigNebulaStorage.cmake
Depends on vesoft-inc/nebula-common#303
> Add .debug_gdb_scripts section to improve debugging experience

- tests/query/v2/test_starts_ends_with.py
Since https://github.com/vesoft-inc/nebula-storage/issues/166 has been solved now tests for starts/ends/with are able to run.
> revert skipped tests

- src/executor/CMakeLists.txt
- src/executor/Executor.cpp
- src/executor/admin/ListenerExecutor.cpp
- src/executor/admin/ListenerExecutor.h
- src/parser/AdminSentences.cpp
- src/parser/AdminSentences.h
- src/parser/Sentence.h
- src/parser/parser.yy
- src/parser/scanner.lex
- src/planner/Admin.h
- src/planner/PlanNode.cpp
- src/planner/PlanNode.h
- src/service/PermissionCheck.cpp
- src/validator/AdminValidator.cpp
- src/validator/AdminValidator.h
- src/validator/Validator.cpp
listener interface, based on https://github.com/vesoft-inc/nebula-common/pull/279, rely on https://github.com/vesoft-inc/nebula-storage/pull/180
> listener interface

- .gitignore
- tests/common/nebula_service.py
- tests/common/nebula_test_suite.py
- tests/common/path_value.py
- tests/common/utils.py
- tests/query/v2/conftest.py
- tests/query/v2/test_get_subgraph.py
- tests/query/v2/test_match.py
- tests/query/v2/utils.py
> Fix value to string in CI

- src/executor/CMakeLists.txt
- src/executor/Executor.cpp
- src/executor/admin/ShowStatusExecutor.cpp
- src/executor/admin/ShowStatusExecutor.h
- src/executor/admin/SubmitJobExecutor.cpp
- src/parser/AdminSentences.cpp
- src/parser/AdminSentences.h
- src/parser/Sentence.h
- src/parser/parser.yy
- src/parser/scanner.lex
- src/parser/test/ParserTest.cpp
- src/parser/test/ScannerTest.cpp
- src/planner/Admin.h
- src/planner/PlanNode.cpp
- src/planner/PlanNode.h
- src/service/PermissionCheck.cpp
- src/validator/AdminValidator.cpp
- src/validator/AdminValidator.h
- src/validator/Validator.cpp
- tests/job/test_jobs.py
The following syntax is supported:
```
submit job statis
show status
```
> Submit job statis && show status

- src/context/Symbols.h
- src/executor/logic/PassThroughExecutor.cpp
- src/executor/query/GetPropExecutor.h
- src/executor/query/IndexScanExecutor.cpp
- src/planner/CMakeLists.txt
- src/planner/PlannersRegister.cpp
- src/planner/Query.cpp
- src/planner/planners/MatchSolver.cpp
- src/planner/planners/MatchSolver.h
- src/planner/planners/MatchVariableLengthPatternIndexScanPlanner.cpp
- src/planner/planners/MatchVariableLengthPatternIndexScanPlanner.h
- src/planner/planners/MatchVertexIndexSeekPlanner.cpp
- src/planner/planners/MatchVertexIndexSeekPlanner.h
- src/util/AnonColGenerator.h
- src/util/AnonVarGenerator.h
- src/util/ExpressionUtils.cpp
- src/util/ExpressionUtils.h
- src/util/ToJson.cpp
- src/util/ToJson.h
- src/validator/MatchValidator.cpp
- src/validator/MatchValidator.h
- src/validator/test/MockSchemaManager.cpp
- src/validator/test/MockSchemaManager.h
- src/validator/test/SymbolsTest.cpp
- tests/common/nebula_service.py
- tests/common/nebula_test_suite.py
- tests/common/utils.py
- tests/query/v2/match/conftest.py
- tests/query/v2/match/test_match_base.py
- tests/query/v2/match/test_variable_length_relationships.py
depends on vesoft-inc/nebula-common#306
```text
> MATCH p= (:player{name:"Tim Duncan"})-[e:like*2..3{likeness:95}]-(v) return p
+-----------------------------------------------------------------------------------------------+
| p                                                                                             |
+-----------------------------------------------------------------------------------------------+
| ("Tim Duncan")<-[like@0]-("Tony Parker")-[like@0]->("Manu Ginobili")<-[like@0]-("Tim Duncan") |
+-----------------------------------------------------------------------------------------------+
| ("Tim Duncan")-[like@0]->("Tony Parker")-[like@0]->("Manu Ginobili")<-[like@0]-("Tim Duncan") |
+----------------------------------------------------------------------------------- …
```
> Support variable length match pattern from 1 to n steps

- src/context/Iterator.cpp
- src/context/Iterator.h
- src/context/QueryExpressionContext.cpp
- src/context/QueryExpressionContext.h
- src/visitor/CollectAllExprsVisitor.cpp
- src/visitor/CollectAllExprsVisitor.h
- src/visitor/DeducePropsVisitor.cpp
- src/visitor/DeducePropsVisitor.h
- src/visitor/DeduceTypeVisitor.cpp
- src/visitor/DeduceTypeVisitor.h
- src/visitor/EvaluableExprVisitor.h
- src/visitor/ExtractFilterExprVisitor.cpp
- src/visitor/ExtractFilterExprVisitor.h
- src/visitor/ExtractPropExprVisitor.cpp
- src/visitor/ExtractPropExprVisitor.h
- src/visitor/FindAnyExprVisitor.cpp
- src/visitor/FindAnyExprVisitor.h
- src/visitor/FoldConstantExprVisitor.cpp
- src/visitor/FoldConstantExprVisitor.h
- src/visitor/RewriteInputPropVisitor.cpp
- src/visitor/RewriteInputPropVisitor.h
- src/visitor/RewriteLabelAttrVisitor.h
- src/visitor/RewriteMatchLabelVisitor.h
- src/visitor/RewriteSymExprVisitor.cpp
- src/visitor/RewriteSymExprVisitor.h
backgroud is https://www.yuque.com/nebulagraph/emchnb/kg2u5m
common depend on https://github.com/vesoft-inc/nebula-common/pull/316
storage.  depend on https://github.com/vesoft-inc/nebula-storage/pull/216
> add getColumn(index) for iter

- src/executor/CMakeLists.txt
- src/executor/Executor.cpp
- src/executor/admin/ShowStatsExecutor.cpp
- src/executor/admin/ShowStatsExecutor.h
- src/executor/admin/SubmitJobExecutor.cpp
- src/parser/AdminSentences.cpp
- src/parser/AdminSentences.h
- src/parser/Sentence.h
- src/parser/parser.yy
- src/parser/scanner.lex
- src/parser/test/ParserTest.cpp
- src/parser/test/ScannerTest.cpp
- src/planner/Admin.h
- src/planner/PlanNode.cpp
- src/planner/PlanNode.h
- src/service/PermissionCheck.cpp
- src/validator/AdminValidator.cpp
- src/validator/Validator.cpp
- tests/job/test_jobs.py
depends on https://github.com/vesoft-inc/nebula-common/pull/320
> Modify status to stats

- .github/workflows/pull_request.yml
- .gitignore
- src/executor/Executor.cpp
- src/executor/admin/SubmitJobExecutor.cpp
- src/executor/maintain/EdgeIndexExecutor.cpp
- src/executor/maintain/EdgeIndexExecutor.h
- src/executor/maintain/TagIndexExecutor.cpp
- src/executor/maintain/TagIndexExecutor.h
- src/parser/AdminSentences.cpp
- src/parser/AdminSentences.h
- src/parser/MaintainSentences.cpp
- src/parser/MaintainSentences.h
- src/parser/Sentence.h
- src/parser/parser.yy
- src/parser/scanner.lex
- src/parser/test/ParserTest.cpp
- src/planner/Admin.h
- src/planner/Maintain.h
- src/planner/PlanNode.cpp
- src/planner/PlanNode.h
- src/service/PermissionCheck.cpp
- src/validator/AdminJobValidator.cpp
- src/validator/AdminJobValidator.h
- src/validator/MaintainValidator.cpp
- src/validator/MaintainValidator.h
- src/validator/Validator.cpp
- tests/common/utils.py
- tests/maintain/test_index.py
Based on https://github.com/vesoft-inc/nebula-storage/pull/192
> show tag/edge index status

- .github/workflows/pull_request.yml
- ci/nebula-test-job.yml
- ci/test-k8s-cluster.sh
- tests/common/utils.py
- tests/query/v1/test_fetch_edges.py
- tests/query/v1/test_fetch_empty.py
- tests/query/v1/test_fetch_vertex.py
- tests/query/v1/test_go.py
- tests/query/v1/test_groupby.py
- tests/query/v1/test_orderby.py
- tests/query/v1/test_set.py
- tests/query/v1/test_yield.py
- tests/query/v2/conftest.py
- tests/query/v2/test_in_not_in.py
- tests/query/v2/test_label_expr.py
- tests/query/v2/test_starts_ends_with.py
Add backoffLimit for job to limit job restarts
Sleep some time for waiting graph service ready
> Fix cluster action

- src/parser/parser.yy
- src/parser/test/ExpressionParsingTest.cpp
- src/planner/planners/MatchSolver.cpp
- src/planner/planners/MatchVariableLengthPatternIndexScanPlanner.cpp
- src/util/ExpressionUtils.h
- src/util/test/ExpressionUtilsTest.cpp
- src/validator/IndexScanValidator.cpp
- src/validator/MatchValidator.cpp
- src/validator/MutateValidator.cpp
- src/visitor/CollectAllExprsVisitor.cpp
- src/visitor/CollectAllExprsVisitor.h
- src/visitor/DeduceTypeVisitor.cpp
- src/visitor/ExprVisitorImpl.cpp
- src/visitor/RewriteLabelAttrVisitor.cpp
- src/visitor/RewriteSymExprVisitor.cpp
- tests/query/v2/match/test_variable_length_relationships.py
Depends on vesoft-inc/nebula-common#326
> Fix crash when rewriting label symbols in match

- src/executor/query/FilterExecutor.cpp
- tests/query/v1/test_go.py
Fixes #445 
Depends on vesoft-inc/nebula-common#329
> Fix filter bug

- src/planner/planners/SequentialPlanner.cpp
- src/validator/FindPathValidator.cpp
- tests/query/v1/test_find_path.py
FIND SHORTEST PATH FROM "Tim Duncan" TO "Nobody","Spur" OVER like,serve UPTO 3 STEPS | LIMIT 3
will crash Because path verificator miss output columns
> add path outputs_  &  test case

- src/context/Iterator.cpp
- src/context/Iterator.h
- src/executor/query/DataJoinExecutor.cpp
- tests/query/v1/test_fetch_vertex.py
fetch prop on player 'Tim Duncan' | go from $-.VertexID over like yield like._dst 
Will Error Because JoinIter Don't support PropIter
> apply propIter to Join

- src/service/GraphService.cpp
- src/service/QueryInstance.cpp
- tests/common/nebula_test_suite.py
depends on https://github.com/vesoft-inc/nebula-common/pull/333
> fix ErrorCode typo

- tests/common/utils.py
- tests/tck/utils/nbv.py
depends on https://github.com/vesoft-inc/nebula-common/pull/341
depends on https://github.com/vesoft-inc/nebula-python/pull/63
> Modify container name

- src/executor/admin/ShowHostsExecutor.cpp
- src/executor/admin/ShowHostsExecutor.h
- src/parser/AdminSentences.h
- src/parser/parser.yy
- src/parser/test/ParserTest.cpp
- src/planner/Admin.h
- src/service/QueryEngine.cpp
- src/validator/AdminValidator.cpp
add three parameters for show hosts 
```
(root@Nebula-Console) [()]> show hosts graph
==================================================================
|  Host       |  Port  |  Status    |  role     |  git_info_sha  |
==================================================================
|  "0.0.0.0"  |  6510  |  "ONLINE"  |  "GRAPH"  |  "c41c305"     |
------------------------------------------------------------------
(root@Nebula-Console) [()]> show hosts meta
=====================================================================
|  Host           |  Port  |  Status    |  role    |  git_info_sha  |
=====================================================================
|  "127.0.0.1"  |  6500  |  "ONLINE"  |  "META"  |  "44f785b9"    | …
```
> let "show hosts" can show git info sha of graph/meta/storage

- .github/workflows/pull_request.yml
- .gitignore
- tests/.gitignore
- tests/Makefile
- tests/query/v1/test_find_path.py
- tests/requirements.txt
- tests/tck/features/job/job.feature
- tests/tck/features/job/snapshot.feature
- tests/tck/features/match/Base.feature
- tests/tck/features/match/VariableLengthRelationship.feature
- tests/tck/features/parser/nebula.feature
Check gherkin feature file code style in CI
> Add gherkin format tool to unify feature files code style

- tests/tck/utils/nbv.py
> Support regex pattern in CI

- .gitignore
- tests/common/csv_import.py
- tests/common/types.py
- tests/common/utils.py
- tests/data/nba/config.yaml
- tests/data/nba/schema.ngql
- tests/data/nba_int_vid/config.yaml
- tests/data/student/config.yaml
- tests/data/student/schema.ngql
- tests/requirements.txt
- tests/tck/conftest.py
- tests/tck/features/parser/Example.feature
- tests/tck/features/parser/Space.feature
Use config.yaml to share same csv data files
> Support to import int data in test framework

- tests/common/comparator.py
- tests/common/dataset_printer.py
- tests/conftest.py
- tests/tck/conftest.py
- tests/tck/features/match/VariableLengthPattern.feature
- tests/tck/features/parser/Example.feature
- tests/tck/features/path/AllPath.feature
- tests/tck/features/path/PathWithoutSameVertices.feature
- tests/tck/features/path/ShortestPath.feature
- tests/tck/utils/nbv.py
- tests/tck/utils/table.py
Use raw value to compare each other. 
Add dataset printer utils class.
> Refactor Value comparator and support regex match in expected results

- tests/Makefile
- tests/tck/utils/mmh2.py
- tests/tck/utils/nbv.py
> CI added support to specify int and hash as vid

- tests/common/utils.py
- tests/tck/conftest.py
- tests/tck/features/subgraph/subgraph.IntVid.feature
- tests/tck/features/subgraph/subgraph.feature
- tests/tck/utils/table.py
> Support define some list variables used in expect result

- src/context/test/CMakeLists.txt
- src/daemons/CMakeLists.txt
- src/executor/test/CMakeLists.txt
- src/optimizer/test/CMakeLists.txt
- src/parser/test/CMakeLists.txt
- src/planner/test/CMakeLists.txt
- src/util/SchemaUtil.cpp
- src/util/test/CMakeLists.txt
- src/validator/test/CMakeLists.txt
- src/visitor/test/CMakeLists.txt
- tests/maintain/test_index.py
- tests/mutate/test_insert_1.py
- tests/tck/features/index/Index.feature
- tests/tck/features/mutate/InsertWithTimeType.feature
depends on https://github.com/vesoft-inc/nebula-common/pull/369
> Delete unuse obj

- src/executor/query/ProjectExecutor.cpp
- src/validator/YieldValidator.cpp
- src/validator/YieldValidator.h
- tests/admin/test_configs.py
- tests/tck/features/bugfix/TestYieldConstantAfterPipe.feature
- tests/tck/features/yield/TestYieldConstantAfterPipe.feature
Now all tests have beed passed in single thread mode.
> Fix yield.

- src/executor/CMakeLists.txt
- src/executor/Executor.cpp
- src/executor/query/AssignExecutor.cpp
- src/executor/query/AssignExecutor.h
- src/executor/test/AssignTest.cpp
- src/executor/test/CMakeLists.txt
- src/planner/PlanNode.cpp
- src/planner/PlanNode.h
- src/planner/Query.cpp
- src/planner/Query.h
Support assigning values ​​to variables during execution
> add assign executor

- .github/workflows/pull_request.yml
- .gitignore
- tests/.gitignore
- tests/Makefile
- tests/common/dataset_printer.py
- tests/common/types.py
- tests/tck/conftest.py
- tests/tck/features/delete/DeleteEdge.IntVid.feature
- tests/tck/features/delete/DeleteEdge.feature
- tests/tck/features/delete/DeleteVertex.IntVid.feature
- tests/tck/features/delete/DeleteVertex.feature
- tests/tck/features/insert/Insert.IntVid.feature
- tests/tck/features/insert/Insert.feature
- tests/tck/features/update/Update.IntVid.feature
- tests/tck/features/update/Update.feature
1. Add location info of feature file when some test cases fails
2. Fix bug about load space description
3. Split TCK and pytest steps
4. Update build type with sanitizer
> Check address sanitizer in github action

- src/context/test/CMakeLists.txt
- src/executor/test/CMakeLists.txt
- src/optimizer/test/CMakeLists.txt
- src/parser/test/CMakeLists.txt
- src/planner/Query.cpp
- src/util/test/CMakeLists.txt
- src/validator/test/CMakeLists.txt
- src/visitor/test/CMakeLists.txt
> Improve project explained columns format and Fix compile errors

- src/validator/LookupValidator.cpp
- src/validator/test/LookupValidatorTest.cpp
For NG-383, I can't repeat the issue. so added some test cases for regression testing.
> fixed bug of invalid expression expression caused graph crash

- src/parser/parser.yy
- src/parser/scanner.lex
- tests/tck/features/agg/Agg.feature
Add the following aggregate functions:
- collect
- collect_set
> add agg functions

- src/validator/GroupByValidator.cpp
- tests/tck/features/agg/Agg.feature
> fix groupby

- src/parser/parser.yy
- src/parser/scanner.lex
- src/parser/test/ScannerTest.cpp
- src/util/ParserUtil.h
- src/visitor/CollectAllExprsVisitor.cpp
- src/visitor/CollectAllExprsVisitor.h
- src/visitor/DeduceTypeVisitor.cpp
- src/visitor/DeduceTypeVisitor.h
- src/visitor/ExprVisitorImpl.cpp
- src/visitor/ExprVisitorImpl.h
- src/visitor/FindAnyExprVisitor.cpp
- src/visitor/FindAnyExprVisitor.h
- src/visitor/FoldConstantExprVisitor.cpp
- src/visitor/FoldConstantExprVisitor.h
- src/visitor/RewriteInputPropVisitor.cpp
- src/visitor/RewriteInputPropVisitor.h
- src/visitor/RewriteLabelAttrVisitor.cpp
- src/visitor/RewriteLabelAttrVisitor.h
- src/visitor/RewriteMatchLabelVisitor.cpp
- src/visitor/RewriteMatchLabelVisitor.h
- src/visitor/RewriteSymExprVisitor.cpp
- src/visitor/RewriteSymExprVisitor.h
- tests/tck/features/expression/reduce.feature
depends on https://github.com/vesoft-inc/nebula-common/pull/346
doc:https://neo4j.com/docs/cypher-manual/current/functions/list/#functions-reduce
> Support reduce expression

- tests/tck/features/match/VariableLengthPattern.feature
- tests/tck/features/match/VariableLengthPattern.intVid.feature
> ut add path filter by dst node

- .github/workflows/pull_request.yml
> Ignore merged PR in github action

- tests/tck/features/match/WithUnwind.feature
Fix [https://github.com/vesoft-inc/nebula-graph/issues/678](https://github.com/vesoft-inc/nebula-graph/issues/678)
Depends on [https://github.com/vesoft-inc/nebula-common/pull/396](https://github.com/vesoft-inc/nebula-common/pull/396)
> fix unwind agg

- tests/tck/features/expression/ListComprehension.feature
- tests/tck/features/expression/predicate.feature
- tests/tck/features/expression/reduce.feature
Based on https://github.com/vesoft-inc/nebula-common/pull/388
> add a test case for  predicate, list comprehension and reduce

- src/validator/MatchValidator.cpp
- tests/tck/features/match/WithUnwind.feature
fix https://github.com/vesoft-inc/nebula-graph/issues/663, fix https://github.com/vesoft-inc/nebula-graph/issues/624
> [Bugfix] Label expression in with clause has default alias: its label name

- src/context/Iterator.cpp
- src/context/Iterator.h
> Move the constructor of Sequential Iterator to source file

- src/context/CMakeLists.txt
- src/context/Iterator.cpp
- src/context/Iterator.h
- src/context/test/IteratorTest.cpp
- src/executor/mutate/DeleteExecutor.cpp
- src/executor/query/GetNeighborsExecutor.cpp
- src/executor/test/FilterTest.cpp
- src/executor/test/LimitTest.cpp
- src/validator/GoValidator.cpp
- tests/tck/features/go/GO.IntVid.feature
- tests/tck/features/go/GO.feature
- tests/tck/features/subgraph/subgraph.IntVid.feature
- tests/tck/features/subgraph/subgraph.feature
This pr improves the performance by improving the `GetNeibotsIter` and improving the execution plan when get the edge props.
```
GO 3 STEP FROM 6597069837088 OVER knows
```
1.0
2.0
```
GO 3 STEP FROM 6597069837088 OVER knows yield knows.`time`
```
1.0
2.0
> Improve iters.

- src/parser/Clauses.cpp
- src/parser/Clauses.h
- src/parser/MutateSentences.cpp
- src/parser/MutateSentences.h
- src/parser/TraverseSentences.cpp
- src/parser/TraverseSentences.h
- src/validator/FetchVerticesValidator.cpp
- src/validator/MutateValidator.cpp
> Reuse the the vertices ast structure.

- src/parser/parser.yy
- tests/tck/features/yield/return.feature
Implement return sentence.
Fixes [https://github.com/vesoft-inc/nebula-graph/issues/390](https://github.com/vesoft-inc/nebula-graph/issues/390)
> return sentence

- src/validator/GoValidator.cpp
- tests/tck/features/go/GO.feature
Fixes [https://github.com/vesoft-inc/nebula-graph/issues/761](https://github.com/vesoft-inc/nebula-graph/issues/761)
> fix where in go clause

- src/context/ast/QueryAstContext.h
- src/planner/match/WithClausePlanner.cpp
- src/planner/match/WithClausePlanner.h
- src/validator/MatchValidator.cpp
- src/validator/test/MatchValidatorTest.cpp
- tests/tck/features/match/WithUnwind.feature
As title.
Fix problems caused by incompatibility: 
fix https://github.com/vesoft-inc/nebula-graph/issues/648 
fix https://github.com/vesoft-inc/nebula-graph/issues/707 
fix https://github.com/vesoft-inc/nebula-graph/issues/668
> Add support to use Aggregation functions with WITH clause

- src/validator/MutateValidator.cpp
- src/validator/test/MutateValidatorTest.cpp
- tests/tck/features/update/Update.feature
Add type check for when clause in update/upsert statement.
Expression in when clause should return bool.
Fixes [https://github.com/vesoft-inc/nebula-graph/issues/762](https://github.com/vesoft-inc/nebula-graph/issues/762)
> fix update/upsert

- src/planner/match/WhereClausePlanner.cpp
- tests/tck/features/match/Base.feature
Fixes [https://jira.nebula-graph.io/browse/NG-451](https://jira.nebula-graph.io/browse/NG-451)
> fix match where clause

- src/util/IndexUtil.cpp
- tests/tck/features/index/Index.feature
> Fix type length of string index column when show create tag index

- src/daemons/GraphDaemon.cpp
- src/service/GraphFlags.cpp
- src/service/GraphFlags.h
- src/service/QueryEngine.cpp
https://jira.nebula-graph.io/browse/NG-456
> use local_ip OR hostName represent graph in meta

- README.md
- src/executor/query/GetNeighborsExecutor.cpp
- src/executor/query/GetVerticesExecutor.cpp
- src/optimizer/CMakeLists.txt
- src/optimizer/OptContext.cpp
- src/optimizer/rule/MergeGetNbrsAndDedupRule.cpp
- src/optimizer/rule/MergeGetNbrsAndDedupRule.h
- src/optimizer/rule/MergeGetNbrsAndProjectRule.cpp
- src/optimizer/rule/MergeGetNbrsAndProjectRule.h
- src/optimizer/rule/MergeGetVerticesAndDedupRule.cpp
- src/optimizer/rule/MergeGetVerticesAndDedupRule.h
- src/optimizer/rule/MergeGetVerticesAndProjectRule.cpp
- src/optimizer/rule/MergeGetVerticesAndProjectRule.h
- src/planner/Logic.cpp
- src/planner/Logic.h
- src/planner/PlanNode.h
- src/planner/Query.cpp
- src/planner/Query.h
- src/util/SchemaUtil.cpp
- tests/Makefile
- tests/common/plan_differ.py
- tests/tck/features/agg/Agg.feature
- tests/tck/features/match/MatchGroupBy.feature
- tests/tck/features/optimizer/MergeGetNbrsDedupProjectRule.feature
- tests/tck/features/optimizer/MergeGetVerticesDedupProjectRule.feature
1. Merge GetVertices and Dedup: GetVertices(dedup=true)
2. Merge GetNeighbors and Dedup: GetNeighbors(dedup=true)
3. Merge GetVertices and Project: GetVertices(srcExpr=projectExpr)
4. Merge GetNeighbors and Project: GetNeighbors(srcExpr=projectExpr)
depends on #679
> Add opt rules to delete redundant dedup and project plan node

- src/planner/match/MatchClausePlanner.cpp
- src/validator/test/QueryValidatorTest.cpp
Query:
```
nebula> MATCH (n)-[]-(m:player{name:"Kyle Anderson"}) RETURN n, m
```
[Old plan](https://dreampuf.github.io/GraphvizOnline/#%20%20digraph%20exec_plan%20%7B%0A%20%20%20%20%20%20rankdir%3DBT%3B%0A%20%20%20%20%20%20%22Project_21%22%5Blabel%3D%22%7BProject_21%7CoutputVar%3A%20%5C%5B%5C%7B%5C%22colNames%5C%22%3A%5C%5B%5C%22n%5C%22%2C%5C%22m%5C%22%5C%5D%2C%5C%22name%5C%22%3A%5C%22__Project_21%5C%22%2C%5C%22type%5C%22%3A%5C%22DATASET%5C%22%5C%7D%5C%5D%7CinputVar%3A%20__Filter_20%7D%22%2C%20shape%3DMrecord%5D%3B%0A%20%20%20%20%20%20%22Filter_20%22-%3E%22Project_21%22%3B%0A%20%20%20%20%20%20%22Filter_20%22%5Blabel%3D%22%7BFilter_20%7CoutputVar%3A%20%5C%5B%5C%7B%5C%22colNames%5C%22%3A%5C%5B%5C%22n%5C%22%2C%5C%22m%5C%22%2C%5C%22__COL_0%5C%22%5C%5D%2C%5C%22name%5C%22%3A%5C%22__Filter_20%5C% …
> Fix expand match execution plan in right direction

- src/planner/ExecutionPlan.cpp
- src/planner/ExecutionPlan.h
- src/service/QueryInstance.cpp
depends on vesoft-inc/nebula-common#436
> Response optimization time to client

- src/executor/query/GetNeighborsExecutor.cpp
- src/executor/query/GetVerticesExecutor.cpp
- src/planner/PlanNode.cpp
- src/planner/PlanNode.h
- src/planner/Planner.cpp
- src/planner/Planner.h
- src/planner/Query.cpp
- src/planner/Query.h
- src/planner/SequentialPlanner.cpp
- src/planner/match/MatchClausePlanner.cpp
- tests/common/csv_import.py
Refactor Join plan node construtor and add readVariable function to cleanup same codes.
Split from vesoft-inc/nebula-graph#796
> Refactor and cleanup

- src/parser/parser.yy
- src/parser/scanner.lex
- src/parser/test/ParserTest.cpp
- src/visitor/DeduceTypeVisitor.cpp
- src/visitor/ExtractPropExprVisitor.cpp
- src/visitor/RewriteInputPropVisitor.cpp
- tests/tck/features/expression/UnaryExpr.feature
Add `IS NULL` and `IS NOT NULL`
Depends on [https://github.com/vesoft-inc/nebula-common/pull/409](https://github.com/vesoft-inc/nebula-common/pull/409)
> add isNull/isNotNull

- tests/common/nebula_service.py
> Specify nebula service port range to avoid conflicts with client connection

- tests/tck/features/expression/RelationalExpr.feature
Fixes [https://github.com/vesoft-inc/nebula-graph/issues/702](https://github.com/vesoft-inc/nebula-graph/issues/702) and fixes [https://github.com/vesoft-inc/nebula-graph/issues/652](https://github.com/vesoft-inc/nebula-graph/issues/652)
Depends on [https://github.com/vesoft-inc/nebula-common/pull/451](https://github.com/vesoft-inc/nebula-common/pull/451)
> add tck case for In and notIn

- .gitignore
- src/visitor/DeduceTypeVisitor.cpp
- tests/tck/features/expression/In.feature
- tests/tck/features/expression/ListComprehension.feature
- tests/tck/features/expression/Predicate.feature
- tests/tck/features/expression/Reduce.feature
fix https://discuss.nebula-graph.com.cn/t/topic/3048/2
> [bugfix] fix deduce type of in expression

- src/parser/parser.yy
- src/planner/SequentialPlanner.cpp
- src/planner/match/MatchPlanner.cpp
- src/util/CMakeLists.txt
- src/util/ParserUtil.cpp
- src/util/ParserUtil.h
- src/validator/Validator.cpp
- src/visitor/CollectAllExprsVisitor.cpp
- src/visitor/DeduceTypeVisitor.cpp
- src/visitor/ExprVisitorImpl.cpp
- src/visitor/FindAnyExprVisitor.cpp
- src/visitor/FoldConstantExprVisitor.cpp
- src/visitor/RewriteInputPropVisitor.cpp
- src/visitor/RewriteLabelAttrVisitor.cpp
- src/visitor/RewriteMatchLabelVisitor.cpp
- src/visitor/RewriteSymExprVisitor.cpp
- tests/tck/features/match/Base.IntVid.feature
- tests/tck/features/match/Base.feature
- tests/tck/features/match/WithUnwind.feature
depend on https://github.com/vesoft-inc/nebula-common/pull/443
> add exists

- src/context/QueryContext.cpp
- src/context/QueryContext.h
- src/executor/Executor.cpp
- src/planner/ExecutionPlan.cpp
- src/planner/ExecutionPlan.h
- src/planner/PlanNode.h
- src/service/QueryInstance.cpp
- src/service/QueryInstance.h
- src/validator/ExplainValidator.cpp
> Move plan description from QueryContext to ExecutionPlan

- tests/Makefile
- tests/data/nba/config.yaml
- tests/data/nba/null.csv
- tests/data/nba/player.csv
- tests/query/bugs/fixed_pr2042.py
- tests/query/stateless/test_lookup.py
- tests/tck/conftest.py
- tests/tck/features/lookup/ByIndex.feature
- tests/tck/features/lookup/ByIndex.intVid.feature
- tests/tck/features/update/Update.IntVid.feature
in addition, strip query string and report tck test case results in gherkin format
> Store nullable data in a separate csv file

- .github/workflows/package.yml
- .github/workflows/release.yml
> fix oss uploading

- tests/tck/features/expression/function/Mathematical.feature
Depends on [https://github.com/vesoft-inc/nebula-common/pull/460](https://github.com/vesoft-inc/nebula-common/pull/460)
> add bit functions tck cases

- src/context/Iterator.cpp
- src/context/Iterator.h
- tests/tck/features/go/GO.IntVid.feature
- tests/tck/features/go/GO.feature
fixes https://github.com/vesoft-inc/nebula-graph/issues/856
> fix getNeighborIter

- .github/workflows/package.yml
- .github/workflows/pull_request.yml
- tests/Makefile
- tests/common/comparator.py
- tests/common/types.py
- tests/common/utils.py
- tests/tck/conftest.py
- tests/tck/features/bugfix/MatchReturnEmptyTag.feature
- tests/tck/features/delete/DeleteEdge.IntVid.feature
- tests/tck/features/delete/DeleteEdge.feature
- tests/tck/features/delete/DeleteVertex.IntVid.feature
- tests/tck/features/fetch/FetchEmpty.feature
- tests/tck/features/index/Index.IntVid.feature
- tests/tck/features/index/Index.feature
- tests/tck/features/insert/Insert.IntVid.feature
- tests/tck/features/insert/Insert.feature
- tests/tck/features/lookup/ByIndex.feature
- tests/tck/features/lookup/ByIndex.intVid.feature
- tests/tck/features/lookup/LookUp.IntVid.feature
- tests/tck/features/lookup/LookUp.feature
- tests/tck/features/mutate/InsertWithTimeType.feature
- tests/tck/features/parser/Example.feature
- tests/tck/features/schema/Schema.feature
- tests/tck/features/ttl/TTL.feature
- tests/tck/features/update/Update.IntVid.feature
- tests/tck/features/update/Update.feature
- tests/tck/features/user/User.feature
> Retry for queries related to schema modifications in CI

- .github/workflows/pull_request.yml
- src/executor/CMakeLists.txt
- src/executor/StorageAccessExecutor.cpp
- src/executor/StorageAccessExecutor.h
- src/executor/query/GetNeighborsExecutor.cpp
- src/executor/query/GetNeighborsExecutor.h
- src/executor/query/GetVerticesExecutor.cpp
- src/executor/test/GetNeighborsTest.cpp
GetVertices and GetNeighbors share the same codes with cpp template partial specialization
> Extract dedup vid request data logics

- package/package.sh
- src/executor/query/GetVerticesExecutor.cpp
- tests/README.md
- tests/tck/features/mutate/InsertWithTimeType.feature
> Fix version bug when packaging

- src/executor/algo/BFSShortestPathExecutor.cpp
> replace multimap with unordered_multimap

- src/validator/AdminValidator.cpp
- tests/admin/test_listener.py
close https://jira.nebula-graph.io/browse/ONCALL-109
depends on https://github.com/vesoft-inc/nebula-common/pull/470
> Add check to add listener hosts and test

- tests/Makefile
> [Simple] Clean *.lock files in Makefile

- package/package.sh
> Fix docker build script

- .github/workflows/pull_request.yml
> Checkout special branch of commom and storage repos

- src/executor/query/AggregateExecutor.cpp
- src/executor/test/AggregateTest.cpp
- tests/tck/features/aggregate/Agg.feature
Fixes [https://jira.nebula-graph.io/browse/NG-501](https://jira.nebula-graph.io/browse/NG-501)
Depends on [https://github.com/vesoft-inc/nebula-common/pull/480](https://github.com/vesoft-inc/nebula-common/pull/480)
> fix agg executor

- src/context/Iterator.cpp
- src/context/test/IteratorTest.cpp
> fix cluster getNeightborIter

- src/optimizer/rule/IndexScanRule.cpp
- src/optimizer/rule/LimitPushDownRule.cpp
- src/optimizer/rule/MergeGetNbrsAndDedupRule.cpp
- src/optimizer/rule/MergeGetNbrsAndProjectRule.cpp
- src/optimizer/rule/MergeGetVerticesAndDedupRule.cpp
- src/optimizer/rule/MergeGetVerticesAndProjectRule.cpp
- src/optimizer/rule/PushFilterDownAggregateRule.cpp
- src/optimizer/rule/PushFilterDownGetNbrsRule.cpp
- src/planner/Logic.cpp
- src/planner/Logic.h
- src/planner/PlanNode.h
- src/planner/Query.cpp
- src/planner/Query.h
PlanNode::clone virtual implementation.
> implement PlanNode clone interface

- src/parser/parser.yy
- tests/tck/features/expression/FunctionCall.feature
some func like date(), datetime() will crash due to its argument_list is nullptr
> fix date() crash

- src/executor/mutate/InsertExecutor.cpp
- src/parser/MaintainSentences.cpp
- src/parser/MutateSentences.cpp
- src/parser/MutateSentences.h
- src/parser/parser.yy
- src/parser/test/ParserTest.cpp
- src/planner/Mutate.cpp
- src/planner/Mutate.h
- src/validator/MutateValidator.cpp
- src/validator/MutateValidator.h
- tests/tck/features/insert/InsertIfNotExists.feature
depend on vesoft-inc/nebula-common#473
vesoft-inc/nebula-storage#413
> Insert if not exist

- src/util/ExpressionUtils.h
- tests/tck/features/expression/Predicate.feature
Fixes [https://github.com/vesoft-inc/nebula/issues/2473](https://github.com/vesoft-inc/nebula/issues/2473)
> fix predicate expression with agg

- tests/tck/features/expression/ListComprehension.feature
- tests/tck/features/expression/Predicate.feature
- tests/tck/features/expression/Reduce.feature
Add tck case for [https://github.com/vesoft-inc/nebula-graph/pull/958](https://github.com/vesoft-inc/nebula-graph/pull/958)
> add tck case

- src/executor/query/FilterExecutor.cpp
Depends on [https://github.com/vesoft-inc/nebula-common/pull/510](https://github.com/vesoft-inc/nebula-common/pull/510)
Depends on [https://github.com/vesoft-inc/nebula-common/pull/511](https://github.com/vesoft-inc/nebula-common/pull/511)
Depends on [https://github.com/vesoft-inc/nebula-common/pull/512](https://github.com/vesoft-inc/nebula-common/pull/512)
Depended by [https://github.com/vesoft-inc/nebula-graph/pull/970](https://github.com/vesoft-inc/nebula-graph/pull/970)
> fix filter executor

- src/parser/MutateSentences.h
- src/parser/parser.yy
- src/validator/MutateValidator.cpp
- tests/tck/features/insert/InsertIfNotExists.feature
refer to https://jira.nebula-graph.io/browse/NG-528
> Insert with default propNames

- src/context/ast/CypherAstContext.h
- src/context/ast/QueryAstContext.h
- src/planner/match/CypherClausePlanner.h
- src/planner/match/Expand.h
- src/planner/match/MatchClausePlanner.cpp
- src/planner/match/MatchPlanner.cpp
- src/planner/match/MatchPlanner.h
- src/planner/match/MatchSolver.cpp
- src/planner/match/MatchSolver.h
- src/planner/match/SegmentsConnector.h
- src/planner/match/StartVidFinder.h
- src/planner/match/VertexIdSeek.h
- src/validator/MatchValidator.h
for Migrate the execution plan of  ngql to the planner file
> change QueryAstContext to CypherAstContext

- src/optimizer/OptGroup.cpp
- src/optimizer/Optimizer.cpp
- src/optimizer/rule/RemoveNoopProjectRule.cpp
- src/planner/Algo.cpp
- src/planner/Algo.h
- src/planner/PlanNode.cpp
- src/planner/PlanNode.h
- src/planner/Query.cpp
- src/planner/Query.h
- src/validator/SetValidator.cpp
- src/validator/test/ValidatorTestBase.cpp
> Rename binary input plan node

- src/optimizer/CMakeLists.txt
- src/optimizer/rule/CombineFilterRule.cpp
- src/optimizer/rule/CombineFilterRule.h
- tests/tck/features/expression/UnaryExpr.feature
- tests/tck/features/optimizer/CombineFilterRule.feature
- tests/tck/features/optimizer/MergeGetVerticesDedupProjectRule.feature
Depends on [https://github.com/vesoft-inc/nebula-graph/pull/972](https://github.com/vesoft-inc/nebula-graph/pull/972)
> combine consecutive filter plan nodes

- tests/tck/features/match/PipeAndVariable.feature
reference https://discuss.nebula-graph.com.cn/t/topic/3853/17?u=yee
> Test pipe and sequential sentences for match

- src/validator/GetSubgraphValidator.cpp
- tests/tck/features/subgraph/subgraph.IntVid.feature
- tests/tck/features/subgraph/subgraph.feature
> Stop expand when reach end for subgraph.

- tests/tck/features/update/Update.feature
refer to
https://github.com/vesoft-inc/nebula-graph/pull/1035/checks?check_run_id=2598008932
> fix ci test error 

- src/planner/match/MatchSolver.cpp
- src/planner/match/MatchSolver.h
- src/util/SchemaUtil.cpp
- src/util/SchemaUtil.h
this interface will also be invoked by findPath
> move getVertexProp to util

- tests/admin/test_permission.py
- tests/common/nebula_test_suite.py
- tests/job/test_jobs.py
- tests/query/stateless/test_range.py
- tests/tck/conftest.py
- tests/tck/features/update/Update.feature
refer to  https://github.com/vesoft-inc/nebula-graph/pull/1035/checks?check_run_id=2618575466
> fix ci test error again

- tests/tck/features/go/GO.feature
As title.
The case was reported in https://github.com/vesoft-inc/nebula-graph/issues/335
> [Simple] Add test case from issue

- tests/tck/features/index/Index.IntVid.feature
- tests/tck/features/update/Update.IntVid.feature
https://github.com/vesoft-inc/nebula-graph/pull/1026/checks?check_run_id=2626248957
> fix ci test error thrid

- src/planner/plan/Query.h
See the error in https://github.com/vesoft-inc/nebula-graph/pull/764/checks?check_run_id=2663425205
> Fix the setter of input of join.

- src/executor/Executor.cpp
- src/planner/plan/PlanNode.h
> Allow executors continue to run except query type plan node

- src/executor/query/GetEdgesExecutor.cpp
- src/executor/query/GetVerticesExecutor.cpp
- src/executor/query/IndexScanExecutor.cpp
- src/planner/match/InnerJoinStrategy.cpp
- src/planner/match/MatchClausePlanner.cpp
- src/planner/plan/PlanNode.h
- src/validator/test/ValidatorTestBase.cpp
depends on vesoft-inc/nebula-common#551
> Cleanup plan node colNamesRef function

- src/optimizer/OptimizerUtils.cpp
- src/optimizer/test/IndexBoundValueTest.cpp
Depends on vesoft-inc/nebula-common#549 and vesoft-inc/nebula-storage#473
> Shrink sizeof Value struct

- src/parser/Clauses.cpp
- src/parser/Clauses.h
- src/util/ParserUtil.cpp
- src/validator/MatchValidator.cpp
- src/validator/MutateValidator.cpp
- src/validator/Validator.cpp
- tests/tck/features/optimizer/PushFilterDownGetNbrsRule.feature
depends on vesoft-inc/nebula-common#552
> Fix expression raw string interface usage

- package/CMakeLists.txt
Issue:
fixes https://github.com/vesoft-inc/nebula-graph/issues/1133
> add listener conf file for make install

- tests/job/test_session.py
- tests/tck/conftest.py
- tests/tck/features/insert/Insert.feature
- tests/tck/features/schema/Schema.feature
https://github.com/vesoft-inc/nebula-graph/runs/2854567731?check_suite_focus=true
https://github.com/vesoft-inc/nebula-graph/runs/2849664295?check_suite_focus=true
> Fix test failed

- src/service/GraphService.cpp
- src/service/GraphService.h
Require https://github.com/vesoft-inc/nebula-common/pull/569
> Update the error code.

- src/visitor/DeduceTypeVisitor.cpp
- tests/tck/features/bugfix/ListSlicingWithNull.feature
> Fix the error when list slicing with null bound.

- src/daemons/GraphDaemon.cpp
- src/executor/admin/SessionExecutor.h
- src/executor/admin/SubmitJobExecutor.cpp
- src/optimizer/Optimizer.h
- src/optimizer/rule/IndexScanRule.cpp
- src/scheduler/AsyncMsgNotifyBasedScheduler.cpp
- src/service/GraphService.cpp
Require https://github.com/vesoft-inc/nebula-common/pull/571     https://github.com/vesoft-inc/nebula-storage/pull/505
> Expose time utils.

- tests/nebula-test-run.py
support remote nebula by using `--address` parameter.
> support tck to test remote nebula graph

- src/planner/Planner.cpp
- src/planner/Planner.h
- src/validator/GetSubgraphValidator.cpp
- src/validator/GetSubgraphValidator.h
- tests/tck/features/bugfix/SubgraphBeforePipe.feature
As title.
Close https://github.com/vesoft-inc/nebula-graph/issues/1168
> Support to use get subgraph before pipe

- tests/nebula-test-run.py
fix tck test,using remote address
> fix tck test,using remote address

- tests/tck/features/bugfix/SubgraphBeforePipe.feature
> [Minor] Remove unused variable definition in TCK

- tests/job/test_jobs.py
As title.
The submitted jobs may or may not be successful in GitHub action, so add a check before executing `stop job xxx`
> Fix jobs pytest failure

- src/executor/Executor.cpp
- src/executor/mutate/DeleteExecutor.cpp
- src/executor/query/DedupExecutor.cpp
- src/planner/plan/Mutate.cpp
- src/planner/plan/Mutate.h
- src/validator/MutateValidator.cpp
- src/validator/test/MutateValidatorTest.cpp
> Dedup vertex/edge before delete.

- src/optimizer/rule/PushFilterDownGetNbrsRule.cpp
- src/optimizer/rule/PushFilterDownGetNbrsRule.h
- tests/tck/features/optimizer/PushFilterDownGetNbrsRule.feature
> Push edge related filters into GetNeighbors

- src/parser/MatchSentence.cpp
- src/parser/MatchSentence.h
- src/parser/parser.yy
- src/validator/MatchValidator.cpp
- src/validator/MatchValidator.h
- tests/tck/features/match/Base.feature
- tests/tck/features/match/With.feature
fix https://github.com/vesoft-inc/nebula-graph/issues/1279
> Support more complete * syntax in WITH and RETURN

- tests/tck/features/go/GO.IntVid.feature
- tests/tck/features/go/GO.feature
> Add Go test cases for lookup pipe scenario

- .github/workflows/pull_request.yml
- tests/tck/features/expression/function/TypeConversion.feature
Depends on https://github.com/vesoft-inc/nebula-common/pull/609
> Add tests of parsing string to int
