src/executor/logic/LoopExecutor.h
src/executor/logic/PassThroughExecutor.h
src/executor/logic/SelectExecutor.h
src/executor/logic/StartExecutor.h
src/planner/Logic.h
src/planner/PlanNode.cpp
src/planner/PlanNode.h
src/validator/Validator.cpp
src/validator/test/ValidatorTestBase.cpp

This PR will simplify the usage of dependencies when don't care about the plan node kind.
In addition, fix logical executors include guard macros.

Pull dependencies fields Up to plan node class

---

src/optimizer/OptGroup.cpp
src/optimizer/OptGroup.h
src/optimizer/OptRule.cpp
src/optimizer/OptRule.h
src/optimizer/Optimizer.cpp
src/optimizer/rule/IndexScanRule.cpp
src/optimizer/rule/IndexScanRule.h
src/optimizer/rule/PushFilterDownGetNbrsRule.cpp
src/optimizer/rule/PushFilterDownGetNbrsRule.h
src/service/QueryInstance.cpp
tests/common/nebula_service.py
tests/nebula-test-run.py

When we add new optimize rules, we must find expected OptGroupExpr twice in match and transform interfaces. This PR try to simplify this process by introducing the pattern match method.

Add pattern match for OptRule

---

src/optimizer/OptimizerUtils.cpp
src/optimizer/OptimizerUtils.h
src/optimizer/rule/IndexScanRule.cpp
src/optimizer/rule/IndexScanRule.h
src/optimizer/test/IndexBoundValueTest.cpp
src/optimizer/test/IndexScanRuleTest.cpp

Some prepare work to modify null encode in index.
1. forbid range scan of bool in lookup, because `IndexColumnHint` can not make range [start, end) work.
2. add more test case for index scan rule test

forbid range scan of bool in lookup

---

src/planner/Algo.cpp

`varPtr->colNames` is used by other plan node, it can't be moved.

fix CartesianProduct addVar bug

---

src/context/Iterator.cpp
src/parser/parser.yy
src/planner/match/MatchClausePlanner.cpp
src/planner/match/MatchClausePlanner.h
src/validator/FetchVerticesValidator.cpp
src/validator/FetchVerticesValidator.h
src/validator/GetSubgraphValidator.cpp
src/validator/MatchValidator.cpp
src/validator/test/MockSchemaManager.h
tests/tck/features/bugfix/MatchReturnEmptyTag.feature

Address a problem that storage does not recognize vertex tag without property
Fix https://jira.nebula-graph.io/browse/NG-344
Updates:
1. add a new interface in metaClient getAllLatestTagSchema()
2. update tck frame to add support for using Examples keyword when loading data into space
3. replace getAllVerTagSchema() with getAllLatestVerTagSchema() in graph
Depends on https://github.com/vesoft-inc/nebula-storage/pull/288 and https://github.com/vesoft-inc/nebula-common/pull/379

Fix match return vertex undefined labels 

---

src/context/ast/QueryAstContext.h
src/executor/query/AggregateExecutor.cpp
src/planner/CMakeLists.txt
src/planner/match/ReturnClausePlanner.cpp
src/planner/match/YieldClausePlanner.cpp
src/planner/match/YieldClausePlanner.h
src/util/ExpressionUtils.cpp
src/util/ExpressionUtils.h
src/validator/GroupByValidator.cpp
src/validator/GroupByValidator.h
src/validator/MatchValidator.cpp
src/validator/MatchValidator.h
src/validator/test/MatchValidatorTest.cpp
src/visitor/RewriteMatchLabelVisitor.cpp
src/visitor/RewriteMatchLabelVisitor.h
tests/tck/features/expression/predicate.feature
tests/tck/features/index/Index.IntVid.feature
tests/tck/features/match/MatchGroupBy.feature
tests/tck/features/schema/Schema.feature

This PR adds the following feature:
- match groupby (eg.`match (n:player) return n, n.age, avg(n.age)+1`)
fixes #594

[PTAL] Match groupby

---

src/parser/MutateSentences.h
src/validator/DownloadValidator.cpp

```
(root@nebula) [t]> DOWNLOAD HDFS "192.168.8.94:9000:/"
[ERROR (-12)]: SemanticError: HDFS path illegal.Should be HDFS://${HDFS_HOST}:${HDFS_PORT}/${HDFS_PATH}
Mon, 22 Feb 2021 18:34:41 CST
(root@nebula) [t]> DOWNLOAD HDFS "hdfs://192.168.8.94:"
[ERROR (-12)]: SemanticError: HDFS path illegal.Should be HDFS://${HDFS_HOST}:${HDFS_PORT}/${HDFS_PATH}
Mon, 22 Feb 2021 18:36:17 CST
(root@nebula) [t]> DOWNLOAD HDFS "hdfs://192.168.8.94:9090"
[ERROR (-12)]: SemanticError: HDFS path illegal.Should be HDFS://${HDFS_HOST}:${HDFS_PORT}/${HDFS_PATH}
Mon, 22 Feb 2021 18:36:21 CST
```

Fix download core problem

---

src/optimizer/OptGroup.cpp
src/optimizer/OptGroup.h
src/planner/PlanNode.cpp
src/planner/PlanNode.h

Release unused symbols will decrease the number of symbols when applying the new rule.

Release unused symbols for plan node when optimizing

---

conf/nebula-graphd.conf.default
conf/nebula-graphd.conf.production
src/daemons/GraphDaemon.cpp

As title
When we start the service with the following script, the log directory will be created in the script.
./scripts/nebula.service -c xxx/etc/nebula-graphd.conf start graphd> /dev/null 2>&1 &
But when we start the service in other ways, because the directory log does not exist, the startup fails.
xxx/bin/nebula-graphd --flagfile xxx/etc/nebula-graphd-1.conf >1.log 2 >&1 &
Therefore, before starting the service, the log directory needs to be created automatically when it does not exist.

Generate log directory, if it does not exist

---

src/parser/parser.yy
src/parser/test/ParserTest.cpp
tests/tck/features/aggregate/Agg.feature

Add error check for aggregate expression in match where clause.

fix match agg check

---

src/validator/MatchValidator.cpp
src/visitor/FoldConstantExprVisitor.cpp
tests/tck/features/match/SeekById.intVid.feature

As title.
Fix https://jira.nebula-graph.io/browse/NG-522
```
(root@nebula) [nba_int]> MATCH (v) WHERE id(v) == -100 RETURN v;
+--------------------------------------+
| v                                    |
+--------------------------------------+
| (-100 :player{age: 32, name: "Tim"}) |
+--------------------------------------+
Got 1 rows (time spent 7222/7811 us)
```

Fix seek by negative vid

---

tests/tck/features/index/TagEdgeIndex.feature

fixes  https://github.com/vesoft-inc/nebula-graph/issues/892
depend on https://github.com/vesoft-inc/nebula-storage/pull/426

check type of index

---

tests/tck/features/go/GO.IntVid.feature

The `$-.src` is always same value, so the result of order by is unstable.

Solve the unstable case for meanless order by.

---

tests/admin/test_parts.py
tests/tck/features/schema/Schema.feature

change error informations

---

src/optimizer/OptimizerUtils.h
src/optimizer/test/IndexBoundValueTest.cpp
src/optimizer/test/IndexScanRuleTest.cpp
tests/tck/features/lookup/LookUp.IntVid.feature
tests/tck/features/lookup/LookUp.feature

As title.
Solve the problem by a naive approach: change the epsilon to a smaller value.

Fix float precision in comparison

---

package/package.sh

when `CMAKE`'s version less than 3.13, the `-S` `-B` `-j` are not supported

Fix package error when cmake's version less than 3.13

---

src/optimizer/CMakeLists.txt
src/optimizer/OptGroup.h
src/optimizer/rule/RemoveNoopProjectRule.cpp
src/optimizer/rule/RemoveNoopProjectRule.h
tests/tck/features/optimizer/PushFilterDownAggregateRule.feature
tests/tck/features/optimizer/RemoveUselessProjectRule.feature

> 
Depends on [https://github.com/vesoft-inc/nebula-graph/pull/938](https://github.com/vesoft-inc/nebula-graph/pull/938)
This PR adds an optRule to prune unnecessary project node in execution plan.
Scenarios for this OptRule:
Old Plan: A plan that looks like `Start->...->Aggregate->Project->...->Root`
Plan after applying rule: `Start->...->Aggregate->...->Root`
Example:
`match (v:player) with v.age+1 as age, count(v.age) as count  return age,count`
Plan after applying rule:

delete unnecessary project node

---

src/validator/test/YieldValidatorTest.cpp
src/visitor/FindVisitor.inl
tests/tck/features/go/GO.IntVid.feature
tests/tck/features/go/GO.feature
tests/tck/features/yield/yield.IntVid.feature
tests/tck/features/yield/yield.feature

Enhance `FindVisitor` to find `LabelExpression` in `LabelAttrExpression`.
Depends on [https://github.com/vesoft-inc/nebula-common/pull/519](https://github.com/vesoft-inc/nebula-common/pull/519)
Depended by [https://github.com/vesoft-inc/nebula-graph/pull/979](https://github.com/vesoft-inc/nebula-graph/pull/979)

enhance FindVisitor

---

src/optimizer/rule/IndexScanRule.cpp
src/planner/match/MatchSolver.cpp

Expression Optimization:
```
A & (B & ( C & D)) => (A & B & C & D)
(hasSameEdgeInPath($v) == false) => !hasSameEdgeInPath($v)
```

Optimize match expression construction

---

src/parser/parser.yy
tests/tck/features/expression/Predicate.feature

As title.
Support query: `match (n:player) WHERE exists(n['name']) return n`
Fixes https://github.com/vesoft-inc/nebula-graph/issues/841
Depends on https://github.com/vesoft-inc/nebula-common/pull/509

[opencypher compatibility] Support using exists with dynamic map

---

src/validator/MatchValidator.cpp
src/validator/MatchValidator.h
src/validator/test/MatchValidatorTest.cpp

1. Check for MATCH sentence alias when edgeProperty expressions are used.
```
(root@nebula) [nba]> match p = (v:player{name:"Tony Parker"})-[e]->(v2) where v._src>0 return e
[ERROR (-12)]: SemanticError: Vertex `v' does not have the src attribute
```
2. Add more intuitive error messages.
```
(root@nebula) [nba]> match p = (v:player{name:"Tony Parker"})-[e]->(v2) return e._src
[ERROR (-12)]: SemanticError: To get the srcID of the edge, use src(e)
```
Fix https://jira.nebula-graph.io/browse/NG-529

Fix alias check

---

src/util/ExpressionUtils.cpp
src/util/ExpressionUtils.h

Just move some functions to cpp.

move util function to cpp file

---

tests/common/plan_differ.py

skip decoding if `operator info` is empty to avoid some tck error.

fix tck parser error

---

src/planner/match/LabelIndexSeek.cpp
src/util/ExpressionUtils.cpp
src/util/ExpressionUtils.h
src/util/test/ExpressionUtilsTest.cpp
tests/common/plan_differ.py
tests/tck/features/optimizer/IndexScanRule.feature

Fixes [https://github.com/vesoft-inc/nebula-graph/issues/948](https://github.com/vesoft-inc/nebula-graph/issues/948)

embed or-filter into IndexScan

---

src/util/ExpressionUtils.cpp
tests/tck/features/aggregate/Agg.feature

fix #1012 
We don't need to pass a `needVisitedTypes` to agg rewriter because the expression kinds that don't need to be visited have an empty function of body implementation.
```
void visit(ConstantExpression *) override {}
void visit(LabelExpression*) override {}
...
```
Expression kinds such as kConstant, kLabelProperty are basic kinds, they are impossible to nest an agg

fix #1012: Collect values from InputExpression crash the nebula graphd

---

conf/nebula-graphd.conf.default
conf/nebula-graphd.conf.production
resources/gflags.json
src/executor/Executor.cpp
src/service/GraphFlags.cpp
src/service/GraphFlags.h
tests/admin/test_configs.py

refer to #1052 
depends on vesoft-inc/nebula-common#541

Check memory usage before starting executor

---

src/executor/CMakeLists.txt
src/executor/Executor.cpp
src/executor/admin/SpaceExecutor.cpp
src/executor/maintain/FTIndexExecutor.cpp
src/executor/maintain/FTIndexExecutor.h
src/parser/MaintainSentences.cpp
src/parser/MaintainSentences.h
src/parser/Sentence.h
src/parser/parser.yy
src/parser/scanner.lex
src/planner/plan/Maintain.cpp
src/planner/plan/Maintain.h
src/planner/plan/PlanNode.cpp
src/planner/plan/PlanNode.h
src/service/PermissionCheck.cpp
src/util/CMakeLists.txt
src/util/FTIndexUtils.cpp
src/util/FTIndexUtils.h
src/validator/LookupValidator.cpp
src/validator/LookupValidator.h
src/validator/MaintainValidator.cpp
src/validator/MaintainValidator.h
src/validator/Validator.cpp
src/validator/test/MockSchemaManager.h

1, Changed full-text index structure, deleted field schema_id
2, Support for creating full-text index against fields
3, Support drop full-text index
4, Support show full-text index
5, Refuse to create full-text index if fixed_string type length > 256 
6, Refuse to drop or alter tag if full-text index exists.
depends on 
* vesoft-inc/nebula-common#530
* vesoft-inc/nebula-storage#460

Support specified columns for full-text index

---

src/parser/GraphScanner.h
src/parser/parser.yy
src/parser/test/ParserTest.cpp
src/util/ExpressionUtils.cpp
src/util/ExpressionUtils.h
src/validator/GoValidator.cpp
src/validator/LookupValidator.cpp
src/validator/MaintainValidator.cpp
src/validator/MatchValidator.cpp
src/validator/YieldValidator.cpp
src/visitor/FoldConstantExprVisitor.cpp
src/visitor/FoldConstantExprVisitor.h
src/visitor/test/FilterTransformTest.cpp
tests/tck/features/go/GO.feature
tests/tck/features/lookup/ByIndex.feature
tests/tck/features/lookup/ByIndex.intVid.feature
tests/tck/features/match/Base.IntVid.feature
tests/tck/features/match/Base.feature
tests/tck/features/schema/Schema.feature
tests/tck/features/yield/yield.IntVid.feature
tests/tck/features/yield/yield.feature

This PR addresses a few known problems:
1. Fix incorrect column name produced by query `yield -9223372036854775808`.
2. Uniform the overflow error awith Neo4j:
```
(root@nebula) [nba]> yield 9223372036854775807 + 1
[ERROR (-8)]: (9223372036854775807+1) cannot be represented as an integer
(root@nebula) [nba]> yield 9223372036854775807/0
[ERROR (-8)]: / by zero
```
3. Fix parsing minimum integer value in binary, oct, hex, and decimal.
4. Integrate overflow check into MATCH and nGQL
Depends on https://github.com/vesoft-inc/nebula-common/pull/531
Fix https://github.com/vesoft-inc/nebula-graph/issues/621, Fix https://github.com/vesoft-inc/nebula-graph/issues/538, FIx https://github.com/vesoft-inc/nebula-graph/issues/534

Check Integer overflow in expression calculation

---

src/context/ast/QueryAstContext.h
src/parser/Clauses.cpp
src/parser/Clauses.h
src/parser/TraverseSentences.cpp
src/parser/TraverseSentences.h
src/parser/parser.yy
src/parser/scanner.lex
src/validator/GoValidator.cpp
src/validator/GoValidator.h
tests/tck/features/go/GO.feature

support setting different limit or sample for each step in GO
For example:
GO 3 STEPS FROM <vid> OVER <e> WHERE [filter1, filter2, filter3] YIELD <expr> LIMIT [n1, n2, n3]
GO 3 STEPS FROM <vid> OVER <e> WHERE [filter1, filter2, filter3] YIELD <expr> SAMPLE [n1, n2, n3]
As well as WHERE Clause

add go step limit OR sample (validate)

---

src/parser/AdminSentences.h
src/validator/AdminValidator.cpp

This PR make sure the data of the "create space on group" sentence on the group you mentioned instead of all the storage nodes.

fix the bug create space on group

---

tests/Makefile
tests/README.md
tests/tck/utils/nbv.py

gherkin-format depends on python 3.8.

Required python 3.7 for test framework

---

src/service/PermissionCheck.cpp
src/service/PermissionCheck.h
src/service/PermissionManager.cpp
src/service/PermissionManager.h
src/validator/Validator.h
tests/admin/test_permission.py

Fix permission when use multi sentences with use space

---

src/validator/GroupByValidator.cpp
src/validator/GroupByValidator.h
tests/tck/features/aggregate/Agg.feature

Fixes [https://github.com/vesoft-inc/nebula-graph/issues/1160](https://github.com/vesoft-inc/nebula-graph/issues/1160)

fix agg type check when nested

---

src/executor/query/GetNeighborsExecutor.cpp
src/executor/query/LeftJoinExecutor.cpp
src/optimizer/OptContext.h
src/optimizer/OptGroup.cpp
src/optimizer/OptGroup.h
src/optimizer/Optimizer.cpp
src/optimizer/Optimizer.h
src/optimizer/rule/IndexScanRule.cpp
src/optimizer/rule/IndexScanRule.h
src/visitor/ExprVisitorImpl.cpp
tests/tck/features/optimizer/PushFilterDownAggregateRule.feature
tests/tck/features/optimizer/PushFilterDownProjectRule.feature

Return all rules when execution plan is not stable

---

src/optimizer/OptimizerUtils.cpp
tests/tck/features/bugfix/StringFlaotAddition.feature

Add cases from https://github.com/vesoft-inc/nebula-graph/issues/1214
Depends on https://github.com/vesoft-inc/nebula-common/pull/579

[Minor] Add cases from Issue

---

src/planner/match/WhereClausePlanner.cpp
src/planner/match/WhereClausePlanner.h
src/planner/match/WithClausePlanner.cpp
src/planner/plan/Query.cpp
tests/tck/features/match/With.feature

To ensure that `stableFilter`(such as `SequentialIter::erase()`) is used only if the `WITH` clause contains `ORDER BY`.

fix filter degradation

---

scripts/nebula.service
scripts/utils.sh

Fix issue: https://github.com/vesoft-inc/nebula-graph/issues/1066

[issue 1066]: enhance service script to return version information for '-v' option

---

tests/Makefile
tests/job/test_jobs.py

1. Fix outdated jobs tests
2. Check the datatypes returned
3. Add job-related tests to `make test`

[Minor] Add job-related pytest

---

README.md

I think that the link of Slack channel should  be the invitation.
Other open source projects are like this, such as Istio, TiDB, Pulsar.
Fix #1262.

Replace Slack home page with Slack invitation

---

src/validator/LookupValidator.cpp
tests/tck/features/lookup/ByIndex.feature
tests/tck/features/lookup/ByIndex.intVid.feature
tests/tck/features/lookup/EdgeIndexFullScan.feature
tests/tck/features/lookup/FullIndexScan.feature
tests/tck/features/lookup/TagIndexFullScan.feature

As title.
After https://github.com/vesoft-inc/nebula-graph/pull/1260
Close https://github.com/vesoft-inc/nebula-graph/issues/1207

Add support in using relational expressions as filters in LOOKUP clause

---

src/context/Iterator.cpp
tests/tck/features/go/GO.feature

https://discuss.nebula-graph.com.cn/t/topic/4923/4

Fix the go return bad_type when the vertex without the tag

---

src/executor/test/FilterTest.cpp
src/optimizer/rule/PushFilterDownLeftJoinRule.cpp
src/optimizer/rule/PushFilterDownProjectRule.cpp
src/planner/match/LabelIndexSeek.cpp
src/util/ExpressionUtils.cpp
src/util/ExpressionUtils.h
src/util/test/ExpressionUtilsTest.cpp
src/validator/FetchEdgesValidator.cpp
src/validator/FetchVerticesValidator.cpp
src/validator/FindPathValidator.cpp
src/validator/GoValidator.cpp
src/validator/GroupByValidator.cpp
src/validator/LookupValidator.cpp
src/validator/MaintainValidator.cpp
src/validator/MatchValidator.cpp
src/validator/YieldValidator.cpp
src/visitor/test/FilterTransformTest.cpp
src/visitor/test/RewriteRelExprVisitorTest.cpp
src/visitor/test/RewriteUnaryNotExprVisitorTest.cpp

Delete the ObjectPool type parameter in ExpressionUtil functions and fix the inconsistency of the Expression's ObjectPool caused by explicitly specifying the ObjectPool.

fix util functions

---

tests/tck/features/expression/FunctionCall.feature

Require https://github.com/vesoft-inc/nebula-common/pull/589

Add more format of datetime.

---

src/executor/query/IndexScanExecutor.cpp
tests/tck/features/lookup/LookUp.IntVid.feature
tests/tck/features/lookup/LookUp.feature

Check whether index is valid at runtime

---

src/optimizer/CMakeLists.txt
src/optimizer/rule/CollapseProjectRule.cpp
src/optimizer/rule/CollapseProjectRule.h
src/optimizer/rule/PushFilterDownAggregateRule.cpp
tests/tck/features/optimizer/CollapseProjectRule.feature
tests/tck/features/optimizer/PushFilterDownLeftJoinRule.feature

Merge consecutive project plan nodes to avoid memory replication, and this may benefit column pruning in some cases.
example: match (v:player) with v, v.age/10 as age, v.name as name, abs(v.age) as abs return age-1 as res
old plan: 
`...->Project(v,age,name,abs)->Project(res)`
plan applying this rule: 
`...->Project(res)` 
(res=v.age/10-1)

[OptRule] Collapse continuous Project plan node

---

src/visitor/FindVisitor.cpp
src/visitor/FindVisitor.h

small change for FindVisitor

---

src/visitor/DeduceTypeVisitor.cpp
tests/tck/features/expression/Attribute.feature

Require https://github.com/vesoft-inc/nebula-common/pull/586
Close #1264

Support get attribute of date/time/datetime.

---

src/planner/match/MatchPlanner.cpp
src/planner/match/MatchPlanner.h
src/validator/YieldValidator.cpp

The CI crash is caused by the empty inputVar on the plan, which is triggered by `CollapseProjectRule`.
This pr fixes inputVar of the first plan node.

fix ci crash
